---
- name: Create New Users
  hosts: all
  become: true
  gather_facts: false
  vars_files:
    - usernames.yml
  tasks:
    - name: Create Users, Home Directory and add to groups 
      user:
        name: "{{ item }}"
        password: '$6$1lT79OkMYvGsfJQW$avSKYkyN5.0limKLK4MP1F0FaRJVtK4BGSGjpkefPAh9YH/k81Wy9IbdX9hcDeTWtsIA0prc6zQdJhyxlaoS1.'
        shell: /bin/bash
        system: no
        state: present
        createhome: yes
        groups:
        append: yes
        home: "/home/{{ item }}"
        update_password: on_create
      with_items:
        - "{{ names }}"
      register: user_status
 
    - name:
      shell: chage -d 0 "{{ item }}"
      with_items:
        - "{{ names }}"
      when: user_status.changed
